name: lisp2dart
description: Experimenting, trying to compile Lisp to Dart Kernel
version: 0.1.0-dev
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/lisp2dart
environment:
  sdk: ">=1.8.0"
dependencies:
  charcode: ^1.0.0
  kernel: ^0.1.0
  string_scanner: ^1.0.0
dev_dependencies:
  test: ^0.12.15
